### ISSUE TITLE
DB::Exception: Index 'skp_idx_indexResponseBody' does not exist

### ISSUE THREAD

**Issue by cangyin** [ClibMouse/ClickHouse#50]
**Describe what's wrong**
I created 2 identical tables, only with different names and data amount, named '10M', '35M' respectively.

Executing `SELECT count(responseBody) FROM 10M WHERE responseBody LIKE '%xyz%'`  succeeds with no error.
But the same SQL results in error when executed on table '35M':
```
bench1 :) select count(responseBody) from 35M where responseBody like '%xyz%'

SELECT count(responseBody)
FROM `35M`
WHERE responseBody LIKE '%xyz%'

Query id: 7305358d-d9e6-4e7d-9e77-9e5deb7c6918


0 rows in set. Elapsed: 0.005 sec.

Received exception from server (version 22.8.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Index 'skp_idx_indexResponseBody' does not exist. (LOGICAL_ERROR)
```

In fact, I once got the same error on '10M', and fixed with `optimize table 10M`, but this didn't work with table '35M'.

**Does it reproduce on recent release?**

I'm just testing on branch `ftsearch`.

**How to reproduce**

* Build ClickHouse on branch `ftsearch`
* using clickhouse-client
* no Non-default settings
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE business.`10M` ON CLUSTER '{cluster}'
(
    `tenant` LowCardinality(String),
    `srcIp` LowCardinality(Nullable(String)),
    `srcPort` Int32,
    `dstIp` LowCardinality(Nullable(String)),
    `dstPort` Int32,
    `requestHead` Nullable(String),
    `responseHead` Nullable(String),
    `requestBody` String,
    `responseBody` String,
    INDEX indexResponseBody (responseBody) TYPE gin(4) GRANULARITY 1
    -- some irrelevant fields are omitted.
)
ENGINE = MergeTree()
PARTITION BY (tenant, toYYYYMMDD(toDate(recordTimestamp)))
PRIMARY KEY uuId
ORDER BY (uuId, recordTimestamp)
SETTINGS index_granularity = 8192;

CREATE TABLE business.`35M` ON CLUSTER '{cluster}'
...... same as `10M`
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
Sample data processed by clickhouse-obfuscator seams not obfuscated enough.

The two tables are populated with same data source. Table '10M' contains 10,000,000 records, table '35M' contains 35,000,000 records.

* Queries to run that lead to unexpected result
```sql
select count(responseBody) from 35M where responseBody like '%xyz%'
```

**Expected behavior**
The query above returns result with no exception.

**Error message and/or stacktrace**
With `clickhouse-client --stacktrace`
```
bench1 :) select count(responseBody) from `35M` where responseBody like '%xyz%'

SELECT count(responseBody)
FROM `35M`
WHERE responseBody LIKE '%xyz%'

Query id: 574b136c-bcba-4be8-9dbf-cc91022cb0fe


0 rows in set. Elapsed: 0.017 sec.

Received exception from server (version 22.8.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Index 'skp_idx_indexResponseBody' does not exist. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
1. DB::GinIndexStoreFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorage>) in /usr/bin/clickhouse
2. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeIndexCondition>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, unsigned long&, unsigned long&, DB::MarkCache*, DB::UncompressedCache*, Poco::Logger*) in /usr/bin/clickhouse
3. ? in /usr/bin/clickhouse
4. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) in /usr/bin/clickhouse
5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
7. ? in /usr/bin/clickhouse
8. start_thread in /usr/lib64/libpthread-2.17.so
9. clone in /usr/lib64/libc-2.17.so
. (LOGICAL_ERROR)
```

**Additional context**
no

**Comment by cangyin** [comment]
Seems that large table will go into this exception.

**Comment by cangyin** [comment]
We need your help. @larryluogit.

**Comment by larryluogit** [comment]
@cangyin 
uuId and recordTimestamp are missing in create table statement. 
do you have a script populate the table?

**Comment by cangyin** [comment]
Those are omitted, now corrected, sorry.

**Comment by cangyin** [comment]
We may have found where the problem is. The INDEXed column cannot be empty (or even with length less than that 'ngrams' specified in gin(n)).

**Comment by kaynewu** [comment]
> @cangyin uuId and recordTimestamp are missing in create table statement. do you have a script populate the table?

We  can reproduce this bugs like this:
`CREATE TABLE ftsearch.test_gin3_short_test
(
    `recordTimestamp` Int64 default now(),
	 `text` String, 
    INDEX gin_text_index(text) TYPE gin(3) GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY (recordTimestamp)
SETTINGS index_granularity = 1024

insert into ftsearch.test_gin3_short_test(text) values('aa')

 select * from ftsearch.test_gin3_short_test where text like 'abc'

 DB::Exception: Received from localhost:9000. DB::Exception: Index 'skp_idx_gin_text_index' does not exist. (LOGICAL_ERROR)
`

It seems like, if a part's data all text column's length is less than 3 , some invert index file will not be created !
![image](https://user-images.githubusercontent.com/5574794/186810733-5fa62ed3-9ca4-47fa-ab3c-4098aca2775e.png)

**Comment by larryluogit** [comment]
https://github.com/ClibMouse/ClickHouse/pull/54
